REQUIRED_COLUMNS = [
    "Id. de tarea ",
    "Nombre de la tarea",
    "Nombre del depósito",
    "Progreso",
    "Priority",
    "Asignado a",
    "Creado por",
    "Fecha de creación",
    "Fecha de inicio",
    "Fecha de vencimiento",
    "Fecha de finalización",
    "Es periódica",
    "Con retraso",
    "Completado por",
    "Elementos de la lista de comprobación completados",
    "Elementos de la lista de comprobación",
    "Etiquetas",
    "Descripción",
]
